@startuml KKM Backend Data Model

' getters and setters are not added to the class diagramm
' same for constructors
class Recipe{
    - m_name: std::string
    - m_kitchen: Kitchen
    - m_plate: Plate
    - m_season: int
    - m_dayTime: enum
    - m_plateType: enum
    - m_portionSize: int
    - m_ingredients: std::vector<RecipeIngredient>
    - m_prepTime: int
    - m_cookTime: int
    - m_totalTime: int
    ---
    + isfeasibleWithStock(): bool
    + checkMissingIngredients(): std::vector<RecipeIngredient>
    + addMissingToList(): void
}

class Kitchen{
    - m_name: std::string
    - m_stock: Stock
    - m_library: std::vector<Recipe>
    ---
    + addToStock(StockIngredient): void
    + addRecipe(Recipe): void
}

class Plate{
    - m_name: std::string
    - m_recipe: Recipe
    - m_season: int
    - m_dayTime: enum
    - m_plateType: enum
    - m_portionSize: float
    - m_expireDate: std::chrono
    ---
    + eatPortion(float): void
}

class Stock{
    - m_ingredients: std:vector<StockIngredient>
    - m_plates: std::vector<Plate>
    - m_kitchen: Kitchen
    ---
    + addToStock(Ingredient): void
    + removeFromStock(Ingredient): void
}

class Ingredient{
    - m_name: std::string
    ---
}

class StockIngredient{
    - m_name: std::string
    - m_expireDate: std::chrono
    - m_quantity: Quantity
    ---
}

class RecipeIngredient{
    - m_name: std::string
    - m_quantity: Quantity
    ---
}

class Quantity{
    - m_unit: std::string
    - m_value: float
    ---
}

class ShoppingList{
    - m_ingredients: std::vector<RecipeIngredient>
    ---
    - addToList(RecipeIngredient): void
    - removeFromList(RecipeIngredient): void
    - clear(): void
}

StockIngredient --|> Ingredient
RecipeIngredient --|> Ingredient
Recipe "1"--"1" Plate
Stock "1"--"n" Plate
Stock "1"--"n" StockIngredient
Recipe "n"--"n" RecipeIngredient
ShoppingList "0,1"--"n" RecipeIngredient
RecipeIngredient "1"--"1" Quantity
Kitchen "n"--"1" Recipe
Kitchen "1"--"1" Stock
StockIngredient "1"--"1" Quantity

@enduml
