@startuml KKM Backend Data Model

' getters and setters are not added to the class diagramm
' same for constructors
class Recipe{
    - m_name: std::string
    - m_plate: Plate
    - m_season: int
    - m_dayTime: enum
    - m_plateType: enum
    - m_portionSize: int
    - m_ingredients: std::vector<RecipeIngredient>
    - m_prepTime: int
    - m_cookTime: int
    - m_totalTime: int
    ---
    + isfeasibleWithStock(Stock): bool
}


class Plate{
    - m_name: std::string
    - m_recipe: Recipe
    - m_season: int
    - m_dayTime: int
    - m_plateType: PlateType
    - m_portionSize: int
    - m_expireDate: std::chrono
}

class Stock{
    - m_ingredients: std:vector<StockIngredient>
    - m_plates: std::vector<Plate>
    ---
}

class Ingredient{
    - m_name: std::string
    ---
}

class StockIngredient{
    - m_name: std::string
    - m_expireDate: std::chrono
    ---
}

class RecipeIngredient{
    - m_name: std::string
    - m_quantity: Quantity
    ---
}

class Quantity{
    - m_unit: std::string
    - m_value: float
    ---
}

class ShoppingList{
    - m_ingredients: std::vector<RecipeIngredient>
    ---
}

StockIngredient --|> Ingredient
RecipeIngredient --|> Ingredient
Recipe "1"--"1" Plate
Stock "1"--"n" Plate
Stock "1"--"n" StockIngredient
Recipe "n"--"n" RecipeIngredient
ShoppingList "0,1"--"n" RecipeIngredient
RecipeIngredient "1"--"1" Quantity

@enduml
